# Generated by Django 5.2.2 on 2025-06-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizsubmission_userrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='submission',
            new_name='submitted_at',
        ),
    ]
