# Generated by Django 5.2.2 on 2025-06-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='bg3.png', null=True, upload_to='category_images'),
        ),
    ]
