# Generated by Django 5.2.2 on 2025-07-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='mode',
            field=models.CharField(choices=[('PRACTICE', 'Practice (MCQ)'), ('TIMED', 'Timed (MCQ)'), ('TF', 'True/False')], default='PRACTICE', max_length=10),
        ),
    ]
