# Generated by Django 5.2.2 on 2025-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='mode',
            field=models.CharField(choices=[('PRACTICE', 'Practice (MCQ)'), ('TIMED', 'Timed (MCQ)'), ('TF', 'True/False'), ('SCENARIO', 'Scenario Based')], default='PRACTICE', max_length=10),
        ),
    ]
