# Generated by Django 5.2.2 on 2025-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
